name: NASA PROJECT CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: use NodeJS version 18
        uses: action/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run build --prefix client
